def get_xgboost_portfolio():
    portfolio = [
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'minmax',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'gbtree',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.013769411401610079,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 6,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.22315656175049542
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'minmax',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'False',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'gbtree',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.06549473796372063,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 8,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.8363250626717315
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'most_frequent',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'normalize',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.12486972885719434,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 10,
            'classifier:xgradient_boosting:min_child_weight': 1,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.4232411495704931,
            'classifier:xgradient_boosting:normalize_type': 'forest',
            'classifier:xgradient_boosting:rate_drop': 0.5041995383310641,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'robust_scaler',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.7636544305811674,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 7,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.9302405099732459,
            'rescaling:robust_scaler:q_max': 0.9455949249981496,
            'rescaling:robust_scaler:q_min': 0.11959475333506663,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.9562117225426169,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'minmax',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.06351820320112957,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 1,
            'classifier:xgradient_boosting:min_child_weight': 1,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.8322678926859829,
            'classifier:xgradient_boosting:normalize_type': 'forest',
            'classifier:xgradient_boosting:rate_drop': 0.5934698269767472,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'quantile_transformer',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.1284674332475333,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 9,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.0224545032282293,
            'rescaling:quantile_transformer:n_quantiles': 1999,
            'rescaling:quantile_transformer:output_distribution': 'normal',
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.3347273072478496,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'most_frequent',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'quantile_transformer',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'True',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.17646979039158242,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 5,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.930442198096948,
            'rescaling:quantile_transformer:n_quantiles': 1999,
            'rescaling:quantile_transformer:output_distribution': 'uniform',
            'categorical_encoding:one_hot_encoding:minimum_fraction':
                0.10684998197642645,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.25076857035510264,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'standardize',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'gbtree',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.11857433141272593,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 10,
            'classifier:xgradient_boosting:min_child_weight': 9,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.9776829393185357
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'quantile_transformer',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'False',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.15836950715369238,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 1,
            'classifier:xgradient_boosting:min_child_weight': 4,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.5036579755376901,
            'rescaling:quantile_transformer:n_quantiles': 1000,
            'rescaling:quantile_transformer:output_distribution': 'uniform',
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.5,
            'classifier:xgradient_boosting:sample_type': 'weighted'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'quantile_transformer',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'False',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.15900687646819875,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 10,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.4462472879784568,
            'rescaling:quantile_transformer:n_quantiles': 1000,
            'rescaling:quantile_transformer:output_distribution': 'normal',
            'classifier:xgradient_boosting:normalize_type': 'forest',
            'classifier:xgradient_boosting:rate_drop': 0.666287928392264,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'none',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'True',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.012736921382550347,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 3,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.018202008679285685,
            'categorical_encoding:one_hot_encoding:minimum_fraction':
                0.27730513467838724,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.9700924648121602,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'most_frequent',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'minmax',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'False',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.2841754101411667,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 9,
            'classifier:xgradient_boosting:min_child_weight': 1,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.3797054777013923,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.003911777976771123,
            'classifier:xgradient_boosting:sample_type': 'weighted'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'standardize',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction':
                'True',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.012944035837733283,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 6,
            'classifier:xgradient_boosting:min_child_weight': 7,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.6960981265065901,
            'categorical_encoding:one_hot_encoding:minimum_fraction':
                0.4884246529015005,
            'classifier:xgradient_boosting:normalize_type': 'forest',
            'classifier:xgradient_boosting:rate_drop': 0.02416407473065445,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'median',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'quantile_transformer',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.07275575009426513,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 7,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.7915610892121238,
            'rescaling:quantile_transformer:n_quantiles': 1000,
            'rescaling:quantile_transformer:output_distribution': 'uniform',
            'classifier:xgradient_boosting:normalize_type': 'forest',
            'classifier:xgradient_boosting:rate_drop': 0.1772024476067046,
            'classifier:xgradient_boosting:sample_type': 'weighted'
            },
        {
            'balancing:strategy': 'none',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'most_frequent',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'robust_scaler',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.05881211731592753,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 10,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.4642188061470379,
            'rescaling:robust_scaler:q_max': 0.8151076148049057,
            'rescaling:robust_scaler:q_min': 0.17519981901846668,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.001089156163230562,
            'classifier:xgradient_boosting:sample_type': 'weighted'
            },
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'one_hot_encoding',
            'classifier:__choice__': 'xgradient_boosting',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'normalize',
            'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
            'classifier:xgradient_boosting:base_score': 0.5,
            'classifier:xgradient_boosting:booster': 'dart',
            'classifier:xgradient_boosting:colsample_bylevel': 1,
            'classifier:xgradient_boosting:colsample_bytree': 1,
            'classifier:xgradient_boosting:gamma': 0,
            'classifier:xgradient_boosting:learning_rate': 0.0186633788542316,
            'classifier:xgradient_boosting:max_delta_step': 0,
            'classifier:xgradient_boosting:max_depth': 6,
            'classifier:xgradient_boosting:min_child_weight': 0,
            'classifier:xgradient_boosting:n_estimators': 512,
            'classifier:xgradient_boosting:reg_alpha': 0,
            'classifier:xgradient_boosting:reg_lambda': 1,
            'classifier:xgradient_boosting:scale_pos_weight': 1,
            'classifier:xgradient_boosting:subsample': 0.3724579437811831,
            'categorical_encoding:one_hot_encoding:minimum_fraction': 0.0005714526899950449,
            'classifier:xgradient_boosting:normalize_type': 'tree',
            'classifier:xgradient_boosting:rate_drop': 0.6682144494540136,
            'classifier:xgradient_boosting:sample_type': 'uniform'
            },
    ]
    return list(reversed(portfolio))


def get_hydra_portfolio(dataset_name):
    back_to_basics_portfolio = [
        {
            'balancing:strategy': 'weighting',
            'categorical_encoding:__choice__': 'no_encoding',
            'classifier:__choice__': 'sgd',
            'imputation:strategy': 'mean',
            'preprocessor:__choice__': 'no_preprocessing',
            'rescaling:__choice__': 'standardize',
            'classifier:sgd:alpha': 0.001,
            'classifier:sgd:average': 'False',
            'classifier:sgd:fit_intercept': 'True',
            'classifier:sgd:learning_rate': 'invscaling',
            'classifier:sgd:loss': 'log',
            'classifier:sgd:penalty': 'l2',
            'classifier:sgd:tol': 0.001,
            'classifier:sgd:eta0': 0.001,
            'classifier:sgd:power_t': 0.5
        },
        {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'minmax',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'gbtree',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.07206420372390847,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 8,
        'classifier:xgradient_boosting:min_child_weight': 2,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.963598325554633
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'random_forest', 'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'standardize',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
        'classifier:random_forest:bootstrap': 'True',
        'classifier:random_forest:criterion': 'entropy',
        'classifier:random_forest:max_depth': 'None',
        'classifier:random_forest:max_features': 0.5888237867972338,
        'classifier:random_forest:max_leaf_nodes': 'None',
        'classifier:random_forest:min_impurity_decrease': 0.0,
        'classifier:random_forest:min_samples_leaf': 1,
        'classifier:random_forest:min_samples_split': 6,
        'classifier:random_forest:min_weight_fraction_leaf': 0.0,
        'classifier:random_forest:n_estimators': 512
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'libsvm_svc',
        'imputation:strategy': 'most_frequent',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'quantile_transformer',
        'classifier:libsvm_svc:C': 3654.540966147889,
        'classifier:libsvm_svc:gamma': 6.318006207166508e-05,
        'classifier:libsvm_svc:kernel': 'rbf',
        'classifier:libsvm_svc:max_iter': -1,
        'classifier:libsvm_svc:shrinking': 'True',
        'classifier:libsvm_svc:tol': 0.001,
        'rescaling:quantile_transformer:n_quantiles': 1999,
        'rescaling:quantile_transformer:output_distribution': 'normal'
        },
    {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'most_frequent',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'robust_scaler',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'gbtree',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.1965277009117998,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 9,
        'classifier:xgradient_boosting:min_child_weight': 0,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.8104416629782811,
        'rescaling:robust_scaler:q_max':
            0.770114387426427,
        'rescaling:robust_scaler:q_min': 0.25,
        'categorical_encoding:one_hot_encoding:minimum_fraction': 0.010000000000000004
        },
    {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'libsvm_svc',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'standardize',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
        'classifier:libsvm_svc:C': 40.606731902031214,
        'classifier:libsvm_svc:gamma': 6.564876030459675e-05,
        'classifier:libsvm_svc:kernel': 'rbf',
        'classifier:libsvm_svc:max_iter': -1,
        'classifier:libsvm_svc:shrinking': 'True',
        'classifier:libsvm_svc:tol': 0.001
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__':
            'no_encoding',
        'classifier:__choice__':
            'xgradient_boosting',
        'imputation:strategy': 'most_frequent',
        'preprocessor:__choice__':
            'no_preprocessing',
        'rescaling:__choice__': 'robust_scaler',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'dart',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.011152367026335312,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 7,
        'classifier:xgradient_boosting:min_child_weight': 0,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.28242028414213455,
        'rescaling:robust_scaler:q_max': 0.8973186794825451,
        'rescaling:robust_scaler:q_min': 0.24570621638110082,
        'classifier:xgradient_boosting:normalize_type': 'tree',
        'classifier:xgradient_boosting:rate_drop': 0.9882748486378379,
        'classifier:xgradient_boosting:sample_type': 'uniform'
        },
    {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'libsvm_svc',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'normalize',
        'classifier:libsvm_svc:C': 19497.299675459475,
        'classifier:libsvm_svc:gamma': 0.10173284191683914,
        'classifier:libsvm_svc:kernel': 'rbf',
        'classifier:libsvm_svc:max_iter': -1,
        'classifier:libsvm_svc:shrinking': 'False',
        'classifier:libsvm_svc:tol': 0.001
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'random_forest',
        'imputation:strategy': 'median',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'minmax',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
        'classifier:random_forest:bootstrap': 'False',
        'classifier:random_forest:criterion': 'entropy',
        'classifier:random_forest:max_depth': 'None',
        'classifier:random_forest:max_features': 0.8044213657552433,
        'classifier:random_forest:max_leaf_nodes': 'None',
        'classifier:random_forest:min_impurity_decrease': 0.0,
        'classifier:random_forest:min_samples_leaf': 1,
        'classifier:random_forest:min_samples_split': 20,
        'classifier:random_forest:min_weight_fraction_leaf': 0.0,
        'classifier:random_forest:n_estimators': 512,
        'categorical_encoding:one_hot_encoding:minimum_fraction': 0.03282706828000629
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'most_frequent',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'robust_scaler',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'dart',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.018206389431325427,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 5,
        'classifier:xgradient_boosting:min_child_weight': 0,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.9396489595915175,
        'rescaling:robust_scaler:q_max': 0.75,
        'rescaling:robust_scaler:q_min': 0.25,
        'classifier:xgradient_boosting:normalize_type': 'tree',
        'classifier:xgradient_boosting:rate_drop': 0.9746609677240772,
        'classifier:xgradient_boosting:sample_type': 'uniform'
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'standardize',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'dart',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.1315825504969415,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 3,
        'classifier:xgradient_boosting:min_child_weight': 8,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.8853108913105691,
        'categorical_encoding:one_hot_encoding:minimum_fraction': 0.001755911029713673,
        'classifier:xgradient_boosting:normalize_type': 'forest',
        'classifier:xgradient_boosting:rate_drop': 0.20418131307618886,
        'classifier:xgradient_boosting:sample_type': 'weighted'
        },
    {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'median',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'minmax',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'dart',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.7751091210648309,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 6,
        'classifier:xgradient_boosting:min_child_weight': 0,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 0.9249463915198634,
        'categorical_encoding:one_hot_encoding:minimum_fraction': 0.00019534484313863735,
        'classifier:xgradient_boosting:normalize_type': 'tree',
        'classifier:xgradient_boosting:rate_drop': 0.3971889372211298,
        'classifier:xgradient_boosting:sample_type': 'weighted'
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'libsvm_svc',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'none',
        'classifier:libsvm_svc:C': 35.540761261825494,
        'classifier:libsvm_svc:gamma': 0.6756541208932203,
        'classifier:libsvm_svc:kernel': 'rbf',
        'classifier:libsvm_svc:max_iter': -1,
        'classifier:libsvm_svc:shrinking': 'True',
        'classifier:libsvm_svc:tol': 0.001
        },
    {
        'balancing:strategy': 'weighting',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'sgd',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'robust_scaler',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False',
        'classifier:sgd:alpha': 0.07884447493435487,
        'classifier:sgd:average': 'True',
        'classifier:sgd:fit_intercept': 'True',
        'classifier:sgd:learning_rate': 'invscaling',
        'classifier:sgd:loss': 'log',
        'classifier:sgd:penalty': 'l2',
        'classifier:sgd:tol': 0.0125683178097985,
        'rescaling:robust_scaler:q_max': 0.9875474680768089,
        'rescaling:robust_scaler:q_min': 0.1339700709497677,
        'classifier:sgd:eta0': 1.3897261665386139e-07,
        'classifier:sgd:power_t': 0.595315001541722
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'one_hot_encoding',
        'classifier:__choice__': 'libsvm_svc',
        'imputation:strategy': 'median',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'minmax',
        'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True',
        'classifier:libsvm_svc:C': 427.6205247249302,
        'classifier:libsvm_svc:gamma': 0.09804794537145273,
        'classifier:libsvm_svc:kernel': 'rbf',
        'classifier:libsvm_svc:max_iter': -1,
        'classifier:libsvm_svc:shrinking': 'True',
        'classifier:libsvm_svc:tol': 0.001,
        'categorical_encoding:one_hot_encoding:minimum_fraction': 0.47426579920754514
        },
    {
        'balancing:strategy': 'none',
        'categorical_encoding:__choice__': 'no_encoding',
        'classifier:__choice__': 'xgradient_boosting',
        'imputation:strategy': 'mean',
        'preprocessor:__choice__': 'no_preprocessing',
        'rescaling:__choice__': 'robust_scaler',
        'classifier:xgradient_boosting:base_score': 0.5,
        'classifier:xgradient_boosting:booster': 'gbtree',
        'classifier:xgradient_boosting:colsample_bylevel': 1,
        'classifier:xgradient_boosting:colsample_bytree': 1,
        'classifier:xgradient_boosting:gamma': 0,
        'classifier:xgradient_boosting:learning_rate': 0.19779625836083606,
        'classifier:xgradient_boosting:max_delta_step': 0,
        'classifier:xgradient_boosting:max_depth': 8,
        'classifier:xgradient_boosting:min_child_weight': 15,
        'classifier:xgradient_boosting:n_estimators': 512,
        'classifier:xgradient_boosting:reg_alpha': 0,
        'classifier:xgradient_boosting:reg_lambda': 1,
        'classifier:xgradient_boosting:scale_pos_weight': 1,
        'classifier:xgradient_boosting:subsample': 1.0,
        'rescaling:robust_scaler:q_max': 0.75,
        'rescaling:robust_scaler:q_min': 0.267081864094218
        },
    ]
    return list(reversed(back_to_basics_portfolio))